// Generated by @wagmi/cli@0.1.5 on 2/15/2023 at 8:22:47 PM
import {
  useContract,
  UseContractConfig,
  useContractRead,
  UseContractReadConfig,
  useContractWrite,
  UseContractWriteConfig,
  usePrepareContractWrite,
  UsePrepareContractWriteConfig,
  useContractEvent,
  UseContractEventConfig,
} from 'wagmi'
import { WriteContractMode, PrepareWriteContractResult } from 'wagmi/actions'

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// AscensionToken
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export const ascensionTokenABI = [
  { stateMutability: 'nonpayable', type: 'constructor', inputs: [] },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'spender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'delegator',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'fromDelegate',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'toDelegate',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'DelegateChanged',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'delegate',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'previousBalance',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'newBalance',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'DelegateVotesChanged',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'role', internalType: 'bytes32', type: 'bytes32', indexed: true },
      {
        name: 'previousAdminRole',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
      },
      {
        name: 'newAdminRole',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
      },
    ],
    name: 'RoleAdminChanged',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'role', internalType: 'bytes32', type: 'bytes32', indexed: true },
      {
        name: 'account',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'sender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'RoleGranted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'role', internalType: 'bytes32', type: 'bytes32', indexed: true },
      {
        name: 'account',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'sender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'RoleRevoked',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'uint256', type: 'uint256', indexed: false },
    ],
    name: 'Snapshot',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Transfer',
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'DEFAULT_ADMIN_ROLE',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'DOMAIN_SEPARATOR',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'MINTER_ROLE',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'SNAPSHOT_ROLE',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'spender', internalType: 'address', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'account', internalType: 'address', type: 'address' },
      { name: 'snapshotId', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'balanceOfAt',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'amount', internalType: 'uint256', type: 'uint256' }],
    name: 'burn',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'account', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'burnFrom',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'cap',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'account', internalType: 'address', type: 'address' },
      { name: 'pos', internalType: 'uint32', type: 'uint32' },
    ],
    name: 'checkpoints',
    outputs: [
      {
        name: '',
        internalType: 'struct ERC20Votes.Checkpoint',
        type: 'tuple',
        components: [
          { name: 'fromBlock', internalType: 'uint32', type: 'uint32' },
          { name: 'votes', internalType: 'uint224', type: 'uint224' },
        ],
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'subtractedValue', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'decreaseAllowance',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'delegatee', internalType: 'address', type: 'address' }],
    name: 'delegate',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'delegatee', internalType: 'address', type: 'address' },
      { name: 'nonce', internalType: 'uint256', type: 'uint256' },
      { name: 'expiry', internalType: 'uint256', type: 'uint256' },
      { name: 'v', internalType: 'uint8', type: 'uint8' },
      { name: 'r', internalType: 'bytes32', type: 'bytes32' },
      { name: 's', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'delegateBySig',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'delegates',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'blockNumber', internalType: 'uint256', type: 'uint256' }],
    name: 'getPastTotalSupply',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'account', internalType: 'address', type: 'address' },
      { name: 'blockNumber', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'getPastVotes',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'role', internalType: 'bytes32', type: 'bytes32' }],
    name: 'getRoleAdmin',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'role', internalType: 'bytes32', type: 'bytes32' },
      { name: 'index', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'getRoleMember',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'role', internalType: 'bytes32', type: 'bytes32' }],
    name: 'getRoleMemberCount',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'getVotes',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'role', internalType: 'bytes32', type: 'bytes32' },
      { name: 'account', internalType: 'address', type: 'address' },
    ],
    name: 'grantRole',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'role', internalType: 'bytes32', type: 'bytes32' },
      { name: 'account', internalType: 'address', type: 'address' },
    ],
    name: 'hasRole',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'addedValue', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'increaseAllowance',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'account', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'mint',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    name: 'nonces',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'numCheckpoints',
    outputs: [{ name: '', internalType: 'uint32', type: 'uint32' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'value', internalType: 'uint256', type: 'uint256' },
      { name: 'deadline', internalType: 'uint256', type: 'uint256' },
      { name: 'v', internalType: 'uint8', type: 'uint8' },
      { name: 'r', internalType: 'bytes32', type: 'bytes32' },
      { name: 's', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'permit',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'role', internalType: 'bytes32', type: 'bytes32' },
      { name: 'account', internalType: 'address', type: 'address' },
    ],
    name: 'renounceRole',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'role', internalType: 'bytes32', type: 'bytes32' },
      { name: 'account', internalType: 'address', type: 'address' },
    ],
    name: 'revokeRole',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'snapshot',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'interfaceId', internalType: 'bytes4', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'snapshotId', internalType: 'uint256', type: 'uint256' }],
    name: 'totalSupplyAt',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
] as const

/**
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export const ascensionTokenAddress = {
  42161: '0x9e724698051DA34994F281bD81C3E7372d1960AE',
} as const

/**
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export const ascensionTokenConfig = {
  address: ascensionTokenAddress,
  abi: ascensionTokenABI,
} as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// React
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Wraps __{@link useContract}__ with `abi` set to __{@link ascensionTokenABI}__.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionToken(
  config: Omit<UseContractConfig, 'abi' | 'address'> & {
    chainId?: keyof typeof ascensionTokenAddress
  } = {} as any,
) {
  return useContract({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    ...config,
  })
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenRead<TFunctionName extends string>(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, TFunctionName>,
    'abi' | 'address'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, TFunctionName>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"DEFAULT_ADMIN_ROLE"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenDefaultAdminRole(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'DEFAULT_ADMIN_ROLE'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'DEFAULT_ADMIN_ROLE',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'DEFAULT_ADMIN_ROLE'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"DOMAIN_SEPARATOR"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenDomainSeparator(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'DOMAIN_SEPARATOR'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'DOMAIN_SEPARATOR',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'DOMAIN_SEPARATOR'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"MINTER_ROLE"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenMinterRole(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'MINTER_ROLE'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'MINTER_ROLE',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'MINTER_ROLE'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"SNAPSHOT_ROLE"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenSnapshotRole(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'SNAPSHOT_ROLE'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'SNAPSHOT_ROLE',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'SNAPSHOT_ROLE'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"allowance"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenAllowance(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'allowance'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'allowance',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'allowance'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"balanceOf"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenBalanceOf(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'balanceOf'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'balanceOf',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'balanceOf'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"balanceOfAt"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenBalanceOfAt(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'balanceOfAt'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'balanceOfAt',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'balanceOfAt'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"cap"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenCap(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'cap'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'cap',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'cap'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"checkpoints"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenCheckpoints(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'checkpoints'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'checkpoints',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'checkpoints'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"decimals"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenDecimals(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'decimals'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'decimals',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'decimals'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"delegates"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenDelegates(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'delegates'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'delegates',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'delegates'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"getPastTotalSupply"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenGetPastTotalSupply(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'getPastTotalSupply'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'getPastTotalSupply',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'getPastTotalSupply'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"getPastVotes"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenGetPastVotes(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'getPastVotes'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'getPastVotes',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'getPastVotes'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"getRoleAdmin"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenGetRoleAdmin(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'getRoleAdmin'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'getRoleAdmin',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'getRoleAdmin'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"getRoleMember"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenGetRoleMember(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'getRoleMember'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'getRoleMember',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'getRoleMember'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"getRoleMemberCount"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenGetRoleMemberCount(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'getRoleMemberCount'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'getRoleMemberCount',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'getRoleMemberCount'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"getVotes"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenGetVotes(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'getVotes'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'getVotes',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'getVotes'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"hasRole"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenHasRole(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'hasRole'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'hasRole',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'hasRole'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"name"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenName(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'name'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'name',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'name'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"nonces"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenNonces(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'nonces'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'nonces',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'nonces'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"numCheckpoints"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenNumCheckpoints(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'numCheckpoints'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'numCheckpoints',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'numCheckpoints'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"supportsInterface"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenSupportsInterface(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'supportsInterface'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'supportsInterface',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'supportsInterface'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"symbol"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenSymbol(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'symbol'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'symbol',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'symbol'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"totalSupply"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenTotalSupply(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'totalSupply'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'totalSupply',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'totalSupply'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"totalSupplyAt"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenTotalSupplyAt(
  config: Omit<
    UseContractReadConfig<typeof ascensionTokenABI, 'totalSupplyAt'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractRead({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'totalSupplyAt',
    ...config,
  } as UseContractReadConfig<typeof ascensionTokenABI, 'totalSupplyAt'>)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenWrite<
  TMode extends WriteContractMode,
  TFunctionName extends string,
  TChainId extends number = keyof typeof ascensionTokenAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof ascensionTokenABI, string>['abi'],
        TFunctionName
      > & { address?: `0x${string}`; chainId?: TChainId }
    : UseContractWriteConfig<TMode, typeof ascensionTokenABI, TFunctionName> & {
        abi?: never
        address?: never
        chainId?: TChainId
      } = {} as any,
) {
  return useContractWrite<TMode, typeof ascensionTokenABI, TFunctionName>({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"approve"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenApprove<
  TMode extends WriteContractMode,
  TChainId extends number = keyof typeof ascensionTokenAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof ascensionTokenABI, 'approve'>['abi'],
        'approve'
      > & {
        address?: `0x${string}`
        chainId?: TChainId
        functionName?: 'approve'
      }
    : UseContractWriteConfig<TMode, typeof ascensionTokenABI, 'approve'> & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'approve'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof ascensionTokenABI, 'approve'>({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'approve',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"burn"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenBurn<
  TMode extends WriteContractMode,
  TChainId extends number = keyof typeof ascensionTokenAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof ascensionTokenABI, 'burn'>['abi'],
        'burn'
      > & { address?: `0x${string}`; chainId?: TChainId; functionName?: 'burn' }
    : UseContractWriteConfig<TMode, typeof ascensionTokenABI, 'burn'> & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'burn'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof ascensionTokenABI, 'burn'>({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'burn',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"burnFrom"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenBurnFrom<
  TMode extends WriteContractMode,
  TChainId extends number = keyof typeof ascensionTokenAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof ascensionTokenABI, 'burnFrom'>['abi'],
        'burnFrom'
      > & {
        address?: `0x${string}`
        chainId?: TChainId
        functionName?: 'burnFrom'
      }
    : UseContractWriteConfig<TMode, typeof ascensionTokenABI, 'burnFrom'> & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'burnFrom'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof ascensionTokenABI, 'burnFrom'>({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'burnFrom',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"decreaseAllowance"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenDecreaseAllowance<
  TMode extends WriteContractMode,
  TChainId extends number = keyof typeof ascensionTokenAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof ascensionTokenABI,
          'decreaseAllowance'
        >['abi'],
        'decreaseAllowance'
      > & {
        address?: `0x${string}`
        chainId?: TChainId
        functionName?: 'decreaseAllowance'
      }
    : UseContractWriteConfig<
        TMode,
        typeof ascensionTokenABI,
        'decreaseAllowance'
      > & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'decreaseAllowance'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof ascensionTokenABI, 'decreaseAllowance'>(
    {
      abi: ascensionTokenABI,
      address: ascensionTokenAddress[42161],
      functionName: 'decreaseAllowance',
      ...config,
    } as any,
  )
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"delegate"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenDelegate<
  TMode extends WriteContractMode,
  TChainId extends number = keyof typeof ascensionTokenAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof ascensionTokenABI, 'delegate'>['abi'],
        'delegate'
      > & {
        address?: `0x${string}`
        chainId?: TChainId
        functionName?: 'delegate'
      }
    : UseContractWriteConfig<TMode, typeof ascensionTokenABI, 'delegate'> & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'delegate'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof ascensionTokenABI, 'delegate'>({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'delegate',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"delegateBySig"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenDelegateBySig<
  TMode extends WriteContractMode,
  TChainId extends number = keyof typeof ascensionTokenAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof ascensionTokenABI,
          'delegateBySig'
        >['abi'],
        'delegateBySig'
      > & {
        address?: `0x${string}`
        chainId?: TChainId
        functionName?: 'delegateBySig'
      }
    : UseContractWriteConfig<
        TMode,
        typeof ascensionTokenABI,
        'delegateBySig'
      > & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'delegateBySig'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof ascensionTokenABI, 'delegateBySig'>({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'delegateBySig',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"grantRole"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenGrantRole<
  TMode extends WriteContractMode,
  TChainId extends number = keyof typeof ascensionTokenAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof ascensionTokenABI,
          'grantRole'
        >['abi'],
        'grantRole'
      > & {
        address?: `0x${string}`
        chainId?: TChainId
        functionName?: 'grantRole'
      }
    : UseContractWriteConfig<TMode, typeof ascensionTokenABI, 'grantRole'> & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'grantRole'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof ascensionTokenABI, 'grantRole'>({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'grantRole',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"increaseAllowance"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenIncreaseAllowance<
  TMode extends WriteContractMode,
  TChainId extends number = keyof typeof ascensionTokenAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof ascensionTokenABI,
          'increaseAllowance'
        >['abi'],
        'increaseAllowance'
      > & {
        address?: `0x${string}`
        chainId?: TChainId
        functionName?: 'increaseAllowance'
      }
    : UseContractWriteConfig<
        TMode,
        typeof ascensionTokenABI,
        'increaseAllowance'
      > & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'increaseAllowance'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof ascensionTokenABI, 'increaseAllowance'>(
    {
      abi: ascensionTokenABI,
      address: ascensionTokenAddress[42161],
      functionName: 'increaseAllowance',
      ...config,
    } as any,
  )
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"mint"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenMint<
  TMode extends WriteContractMode,
  TChainId extends number = keyof typeof ascensionTokenAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof ascensionTokenABI, 'mint'>['abi'],
        'mint'
      > & { address?: `0x${string}`; chainId?: TChainId; functionName?: 'mint' }
    : UseContractWriteConfig<TMode, typeof ascensionTokenABI, 'mint'> & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'mint'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof ascensionTokenABI, 'mint'>({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'mint',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"permit"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenPermit<
  TMode extends WriteContractMode,
  TChainId extends number = keyof typeof ascensionTokenAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof ascensionTokenABI, 'permit'>['abi'],
        'permit'
      > & {
        address?: `0x${string}`
        chainId?: TChainId
        functionName?: 'permit'
      }
    : UseContractWriteConfig<TMode, typeof ascensionTokenABI, 'permit'> & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'permit'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof ascensionTokenABI, 'permit'>({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'permit',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"renounceRole"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenRenounceRole<
  TMode extends WriteContractMode,
  TChainId extends number = keyof typeof ascensionTokenAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof ascensionTokenABI,
          'renounceRole'
        >['abi'],
        'renounceRole'
      > & {
        address?: `0x${string}`
        chainId?: TChainId
        functionName?: 'renounceRole'
      }
    : UseContractWriteConfig<
        TMode,
        typeof ascensionTokenABI,
        'renounceRole'
      > & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'renounceRole'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof ascensionTokenABI, 'renounceRole'>({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'renounceRole',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"revokeRole"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenRevokeRole<
  TMode extends WriteContractMode,
  TChainId extends number = keyof typeof ascensionTokenAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof ascensionTokenABI,
          'revokeRole'
        >['abi'],
        'revokeRole'
      > & {
        address?: `0x${string}`
        chainId?: TChainId
        functionName?: 'revokeRole'
      }
    : UseContractWriteConfig<TMode, typeof ascensionTokenABI, 'revokeRole'> & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'revokeRole'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof ascensionTokenABI, 'revokeRole'>({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'revokeRole',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"snapshot"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenSnapshot<
  TMode extends WriteContractMode,
  TChainId extends number = keyof typeof ascensionTokenAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof ascensionTokenABI, 'snapshot'>['abi'],
        'snapshot'
      > & {
        address?: `0x${string}`
        chainId?: TChainId
        functionName?: 'snapshot'
      }
    : UseContractWriteConfig<TMode, typeof ascensionTokenABI, 'snapshot'> & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'snapshot'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof ascensionTokenABI, 'snapshot'>({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'snapshot',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"transfer"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenTransfer<
  TMode extends WriteContractMode,
  TChainId extends number = keyof typeof ascensionTokenAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<typeof ascensionTokenABI, 'transfer'>['abi'],
        'transfer'
      > & {
        address?: `0x${string}`
        chainId?: TChainId
        functionName?: 'transfer'
      }
    : UseContractWriteConfig<TMode, typeof ascensionTokenABI, 'transfer'> & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'transfer'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof ascensionTokenABI, 'transfer'>({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'transfer',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"transferFrom"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenTransferFrom<
  TMode extends WriteContractMode,
  TChainId extends number = keyof typeof ascensionTokenAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        TMode,
        PrepareWriteContractResult<
          typeof ascensionTokenABI,
          'transferFrom'
        >['abi'],
        'transferFrom'
      > & {
        address?: `0x${string}`
        chainId?: TChainId
        functionName?: 'transferFrom'
      }
    : UseContractWriteConfig<
        TMode,
        typeof ascensionTokenABI,
        'transferFrom'
      > & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'transferFrom'
      } = {} as any,
) {
  return useContractWrite<TMode, typeof ascensionTokenABI, 'transferFrom'>({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'transferFrom',
    ...config,
  } as any)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function usePrepareAscensionTokenWrite<TFunctionName extends string>(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ascensionTokenABI, TFunctionName>,
    'abi' | 'address'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    ...config,
  } as UsePrepareContractWriteConfig<typeof ascensionTokenABI, TFunctionName>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"approve"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function usePrepareAscensionTokenApprove(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'approve'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'approve',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'approve'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"burn"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function usePrepareAscensionTokenBurn(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'burn'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'burn',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'burn'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"burnFrom"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function usePrepareAscensionTokenBurnFrom(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'burnFrom'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'burnFrom',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'burnFrom'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"decreaseAllowance"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function usePrepareAscensionTokenDecreaseAllowance(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof ascensionTokenABI,
      'decreaseAllowance'
    >,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'decreaseAllowance',
    ...config,
  } as UsePrepareContractWriteConfig<
    typeof ascensionTokenABI,
    'decreaseAllowance'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"delegate"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function usePrepareAscensionTokenDelegate(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'delegate'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'delegate',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'delegate'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"delegateBySig"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function usePrepareAscensionTokenDelegateBySig(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'delegateBySig'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'delegateBySig',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'delegateBySig'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"grantRole"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function usePrepareAscensionTokenGrantRole(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'grantRole'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'grantRole',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'grantRole'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"increaseAllowance"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function usePrepareAscensionTokenIncreaseAllowance(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof ascensionTokenABI,
      'increaseAllowance'
    >,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'increaseAllowance',
    ...config,
  } as UsePrepareContractWriteConfig<
    typeof ascensionTokenABI,
    'increaseAllowance'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"mint"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function usePrepareAscensionTokenMint(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'mint'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'mint',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'mint'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"permit"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function usePrepareAscensionTokenPermit(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'permit'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'permit',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'permit'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"renounceRole"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function usePrepareAscensionTokenRenounceRole(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'renounceRole'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'renounceRole',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'renounceRole'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"revokeRole"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function usePrepareAscensionTokenRevokeRole(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'revokeRole'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'revokeRole',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'revokeRole'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"snapshot"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function usePrepareAscensionTokenSnapshot(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'snapshot'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'snapshot',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'snapshot'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"transfer"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function usePrepareAscensionTokenTransfer(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'transfer'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'transfer',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'transfer'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ascensionTokenABI}__ and `functionName` set to `"transferFrom"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function usePrepareAscensionTokenTransferFrom(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'transferFrom'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    functionName: 'transferFrom',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ascensionTokenABI, 'transferFrom'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link ascensionTokenABI}__.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenEvent<TEventName extends string>(
  config: Omit<
    UseContractEventConfig<typeof ascensionTokenABI, TEventName>,
    'abi' | 'address'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractEvent({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    ...config,
  } as UseContractEventConfig<typeof ascensionTokenABI, TEventName>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link ascensionTokenABI}__ and `eventName` set to `"Approval"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenApprovalEvent(
  config: Omit<
    UseContractEventConfig<typeof ascensionTokenABI, 'Approval'>,
    'abi' | 'address' | 'eventName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractEvent({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    eventName: 'Approval',
    ...config,
  } as UseContractEventConfig<typeof ascensionTokenABI, 'Approval'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link ascensionTokenABI}__ and `eventName` set to `"DelegateChanged"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenDelegateChangedEvent(
  config: Omit<
    UseContractEventConfig<typeof ascensionTokenABI, 'DelegateChanged'>,
    'abi' | 'address' | 'eventName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractEvent({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    eventName: 'DelegateChanged',
    ...config,
  } as UseContractEventConfig<typeof ascensionTokenABI, 'DelegateChanged'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link ascensionTokenABI}__ and `eventName` set to `"DelegateVotesChanged"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenDelegateVotesChangedEvent(
  config: Omit<
    UseContractEventConfig<typeof ascensionTokenABI, 'DelegateVotesChanged'>,
    'abi' | 'address' | 'eventName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractEvent({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    eventName: 'DelegateVotesChanged',
    ...config,
  } as UseContractEventConfig<typeof ascensionTokenABI, 'DelegateVotesChanged'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link ascensionTokenABI}__ and `eventName` set to `"RoleAdminChanged"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenRoleAdminChangedEvent(
  config: Omit<
    UseContractEventConfig<typeof ascensionTokenABI, 'RoleAdminChanged'>,
    'abi' | 'address' | 'eventName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractEvent({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    eventName: 'RoleAdminChanged',
    ...config,
  } as UseContractEventConfig<typeof ascensionTokenABI, 'RoleAdminChanged'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link ascensionTokenABI}__ and `eventName` set to `"RoleGranted"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenRoleGrantedEvent(
  config: Omit<
    UseContractEventConfig<typeof ascensionTokenABI, 'RoleGranted'>,
    'abi' | 'address' | 'eventName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractEvent({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    eventName: 'RoleGranted',
    ...config,
  } as UseContractEventConfig<typeof ascensionTokenABI, 'RoleGranted'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link ascensionTokenABI}__ and `eventName` set to `"RoleRevoked"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenRoleRevokedEvent(
  config: Omit<
    UseContractEventConfig<typeof ascensionTokenABI, 'RoleRevoked'>,
    'abi' | 'address' | 'eventName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractEvent({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    eventName: 'RoleRevoked',
    ...config,
  } as UseContractEventConfig<typeof ascensionTokenABI, 'RoleRevoked'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link ascensionTokenABI}__ and `eventName` set to `"Snapshot"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenSnapshotEvent(
  config: Omit<
    UseContractEventConfig<typeof ascensionTokenABI, 'Snapshot'>,
    'abi' | 'address' | 'eventName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractEvent({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    eventName: 'Snapshot',
    ...config,
  } as UseContractEventConfig<typeof ascensionTokenABI, 'Snapshot'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link ascensionTokenABI}__ and `eventName` set to `"Transfer"`.
 *
 * [__View Contract on Arbitrum One Arbiscan__](https://arbiscan.io/address/0x9e724698051DA34994F281bD81C3E7372d1960AE)
 */
export function useAscensionTokenTransferEvent(
  config: Omit<
    UseContractEventConfig<typeof ascensionTokenABI, 'Transfer'>,
    'abi' | 'address' | 'eventName'
  > & { chainId?: keyof typeof ascensionTokenAddress } = {} as any,
) {
  return useContractEvent({
    abi: ascensionTokenABI,
    address: ascensionTokenAddress[42161],
    eventName: 'Transfer',
    ...config,
  } as UseContractEventConfig<typeof ascensionTokenABI, 'Transfer'>)
}
