import { ChainId } from '@usedapp/core'

export const RPC: { [chainId in ChainId]?: string } = {
  [ChainId.Hardhat]: 'http://localhost:8545',
  [ChainId.ArbitrumRinkeby]: 'https://rinkeby.arbitrum.io/rpc',
  [ChainId.Arbitrum]: 'https://arb1.arbitrum.io/rpc',
  [ChainId.Mainnet]: 'https://rpc.ankr.com/eth',
  [ChainId.Rinkeby]: 'https://eth-rinkeby.alchemyapi.io/v2/iF972RTEF1QUpvKqswWivu4DmvUVYNSr',
  [ChainId.Fantom]: 'https://rpcapi.fantom.network',
  [ChainId.Polygon]: 'https://rpc-mainnet.matic.network',
  [ChainId.xDai]: 'https://rpc.xdaichain.com',
  [ChainId.BSC]: 'https://bsc-dataseed.binance.org/',
  [ChainId.BSCTestnet]: 'https://data-seed-prebsc-2-s3.binance.org:8545',
  [ChainId.Avalanche]: 'https://api.avax.network/ext/bc/C/rpc',
  [ChainId.Harmony]: 'https://api.harmony.one',
  [ChainId.Palm]: 'https://palm-mainnet.infura.io/v3/da5fbfafcca14b109e2665290681e267',
}

export const CHAIN_NAME: { [chainId in ChainId]?: string } = {
  [ChainId.Hardhat]: 'Hardhat',
  [ChainId.ArbitrumRinkeby]: 'Arbtest',
  [ChainId.Arbitrum]: 'Arbitrum',
  [ChainId.Mainnet]: 'Ethereum',
  [ChainId.Ropsten]: 'Ropsten',
  [ChainId.Rinkeby]: 'Rinkeby',
  [ChainId.Goerli]: 'Gorli',
  [ChainId.Kovan]: 'Kovan',
  [ChainId.Fantom]: 'Fantom',
  [ChainId.Polygon]: 'Polygon',
  [ChainId.xDai]: 'XDAI',
  [ChainId.BSC]: 'BSC',
  [ChainId.BSCTestnet]: 'BSCtest',
  [ChainId.Avalanche]: 'Avalanche',
  [ChainId.Harmony]: 'Harmony',
  [ChainId.Palm]: 'PALM',
}

export const CHAIN_IMG: { [chainId in ChainId]?: string } = {
  [ChainId.Hardhat]: '/images/networks/mainnet-network.jpg',
  [ChainId.ArbitrumRinkeby]: '/images/networks/arbitrum-network.jpg',
  [ChainId.Arbitrum]: '/images/networks/arbitrum-network.jpg',
  [ChainId.Mainnet]: '/images/networks/mainnet-network.jpg',
  [ChainId.Ropsten]: '/images/networks/mainnet-network.jpg',
  [ChainId.Rinkeby]: '/images/networks/mainnet-network.jpg',
  [ChainId.Goerli]: '/images/networks/mainnet-network.jpg',
  [ChainId.Kovan]: '/images/networks/mainnet-network.jpg',
  [ChainId.Fantom]: '/images/networks/fantom-network.jpg',
  [ChainId.Polygon]: '/images/networks/polygon-network.jpg',
  [ChainId.xDai]: '/images/networks/xdai-network.jpg',
  [ChainId.BSC]: '/images/networks/bsc-network.jpg',
  [ChainId.BSCTestnet]: '/images/networks/bsc-network.jpg',
  [ChainId.Avalanche]: '/images/networks/avalanche-network.jpg',
  [ChainId.Harmony]: '/images/networks/harmony-network.jpg',
  [ChainId.Palm]: '/images/networks/palm-network.jpg',
}

export const CHAIN_SYMBOL: { [chainId in ChainId]?: string } = {
  [ChainId.Hardhat]: 'ETH',
  [ChainId.ArbitrumRinkeby]: 'aETH',
  [ChainId.Arbitrum]: 'aETH',
  [ChainId.Mainnet]: 'ETH',
  [ChainId.Ropsten]: 'rETH',
  [ChainId.Rinkeby]: 'rETH',
  [ChainId.Goerli]: 'rETH',
  [ChainId.Kovan]: 'ETH',
  [ChainId.Fantom]: 'FTM',
  [ChainId.Polygon]: 'MATIC',
  [ChainId.xDai]: 'XDAI',
  [ChainId.BSC]: 'BSC',
  [ChainId.BSCTestnet]: 'BSC',
  [ChainId.Avalanche]: 'AVAX',
  [ChainId.Harmony]: 'HARM',
  [ChainId.Palm]: 'PALM',
}
