/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SniperRequirementsInterface extends ethers.utils.Interface {
  functions: {
    "admin()": FunctionFragment;
    "excluded(address)": FunctionFragment;
    "requiredBalance()": FunctionFragment;
    "setExcluded(address,bool)": FunctionFragment;
    "setRequiredBalance(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(functionFragment: "excluded", values: [string]): string;
  encodeFunctionData(
    functionFragment: "requiredBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setExcluded",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setRequiredBalance",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "excluded", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requiredBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExcluded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRequiredBalance",
    data: BytesLike
  ): Result;

  events: {};
}

export class SniperRequirements extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SniperRequirementsInterface;

  functions: {
    admin(overrides?: CallOverrides): Promise<[string]>;

    excluded(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    requiredBalance(overrides?: CallOverrides): Promise<[BigNumber]>;

    setExcluded(
      newExcluded: string,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRequiredBalance(
      newBalance: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  admin(overrides?: CallOverrides): Promise<string>;

  excluded(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  requiredBalance(overrides?: CallOverrides): Promise<BigNumber>;

  setExcluded(
    newExcluded: string,
    status: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRequiredBalance(
    newBalance: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    admin(overrides?: CallOverrides): Promise<string>;

    excluded(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    requiredBalance(overrides?: CallOverrides): Promise<BigNumber>;

    setExcluded(
      newExcluded: string,
      status: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setRequiredBalance(
      newBalance: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    admin(overrides?: CallOverrides): Promise<BigNumber>;

    excluded(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    requiredBalance(overrides?: CallOverrides): Promise<BigNumber>;

    setExcluded(
      newExcluded: string,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRequiredBalance(
      newBalance: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    excluded(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    requiredBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setExcluded(
      newExcluded: string,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRequiredBalance(
      newBalance: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
