/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { AppDataFacet, AppDataFacetInterface } from "../AppDataFacet";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "address",
        name: "_sToken",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "sToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101dd806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063485cc955146100465780639ebdf12c1461005b578063fc0c546a14610084575b600080fd5b610059610054366004610174565b610095565b005b6001546001600160a01b03165b6040516001600160a01b03909116815260200160405180910390f35b6000546001600160a01b0316610068565b61009d6100cb565b600080546001600160a01b039384166001600160a01b03199182161790915560018054929093169116179055565b7fc8fcad8db84d3cc18b4c41d551ea0ee66dd599cde068d998e57d5e09332c131c600401546001600160a01b031633146101565760405162461bcd60e51b815260206004820152602260248201527f4c69624469616d6f6e643a204d75737420626520636f6e7472616374206f776e60448201526132b960f11b606482015260840160405180910390fd5b565b80356001600160a01b038116811461016f57600080fd5b919050565b6000806040838503121561018757600080fd5b61019083610158565b915061019e60208401610158565b9050925092905056fea26469706673582212207901010bfb65961a84698411f4b678c95f5bfd79b11b9e16d9664345329d7d3564736f6c63430008090033";

export class AppDataFacet__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<AppDataFacet> {
    return super.deploy(overrides || {}) as Promise<AppDataFacet>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): AppDataFacet {
    return super.attach(address) as AppDataFacet;
  }
  connect(signer: Signer): AppDataFacet__factory {
    return super.connect(signer) as AppDataFacet__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AppDataFacetInterface {
    return new utils.Interface(_abi) as AppDataFacetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AppDataFacet {
    return new Contract(address, _abi, signerOrProvider) as AppDataFacet;
  }
}
