/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ERC20DistributorStorage,
  ERC20DistributorStorageInterface,
} from "../ERC20DistributorStorage";

const _abi = [
  {
    inputs: [],
    name: "POSITION",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50609b8061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063355ac59614602d575b600080fd5b60537f0e6b1d0fb2408f41b7e81ef0487c262f883c2978d7bb92e4242ebf600ab5920681565b60405190815260200160405180910390f3fea2646970667358221220dc44553181c2a07212349c0819a4a7182f1cec1514fbe2a9a60c5ecef90e787e64736f6c63430008090033";

export class ERC20DistributorStorage__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ERC20DistributorStorage> {
    return super.deploy(overrides || {}) as Promise<ERC20DistributorStorage>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ERC20DistributorStorage {
    return super.attach(address) as ERC20DistributorStorage;
  }
  connect(signer: Signer): ERC20DistributorStorage__factory {
    return super.connect(signer) as ERC20DistributorStorage__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC20DistributorStorageInterface {
    return new utils.Interface(_abi) as ERC20DistributorStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC20DistributorStorage {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC20DistributorStorage;
  }
}
