/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  SniperRequirements,
  SniperRequirementsInterface,
} from "../SniperRequirements";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "admin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "excluded",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "requiredBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newExcluded",
        type: "address",
      },
      {
        internalType: "bool",
        name: "status",
        type: "bool",
      },
    ],
    name: "setExcluded",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newBalance",
        type: "uint256",
      },
    ],
    name: "setRequiredBalance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50600080546001600160a01b03191633179055610277806100326000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c806308560ace1461005c5780632836be2414610078578063429cead11461008d5780636f6e9f1e146100c0578063f851a440146100d3575b600080fd5b61006560015481565b6040519081526020015b60405180910390f35b61008b6100863660046101a7565b6100fe565b005b6100b061009b3660046101e3565b60026020526000908152604090205460ff1681565b604051901515815260200161006f565b61008b6100ce366004610205565b61015c565b6000546100e6906001600160a01b031681565b6040516001600160a01b03909116815260200161006f565b6000546001600160a01b031633146101315760405162461bcd60e51b81526004016101289061021e565b60405180910390fd5b6001600160a01b03919091166000908152600260205260409020805460ff1916911515919091179055565b6000546001600160a01b031633146101865760405162461bcd60e51b81526004016101289061021e565b600155565b80356001600160a01b03811681146101a257600080fd5b919050565b600080604083850312156101ba57600080fd5b6101c38361018b565b9150602083013580151581146101d857600080fd5b809150509250929050565b6000602082840312156101f557600080fd5b6101fe8261018b565b9392505050565b60006020828403121561021757600080fd5b5035919050565b6020808252600990820152682727aa1020a226a4a760b91b60408201526060019056fea264697066735822122055342a42e3fe03079d7b9dfe04c960e3548e18298d376d1163aafaf653fcbdf264736f6c63430008090033";

export class SniperRequirements__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SniperRequirements> {
    return super.deploy(overrides || {}) as Promise<SniperRequirements>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SniperRequirements {
    return super.attach(address) as SniperRequirements;
  }
  connect(signer: Signer): SniperRequirements__factory {
    return super.connect(signer) as SniperRequirements__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SniperRequirementsInterface {
    return new utils.Interface(_abi) as SniperRequirementsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SniperRequirements {
    return new Contract(address, _abi, signerOrProvider) as SniperRequirements;
  }
}
